config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    path_names: { sign_in: 'login', sign_out: 'logout', password: 'passwords' },
    controllers: { sessions: 'users/sessions', passwords: 'users/passwords' }
  root to: "test_logins#index", as: :root
  namespace :admin do
    root to: 'users#index'
    resources :users
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  ROLE_ADMIN_SYSTEM = 1
  ROLE_AREA_SYSTEM = 2

  ROLES = {
    ROLE_ADMIN_SYSTEM => I18n.t("admin.user_type.superadmin"),
    ROLE_AREA_SYSTEM => I18n.t("admin.user_type.area"),
  }

  def role label=false
    label && ROLES.include?(read_attribute(:user_type)) ? ROLES[read_attribute(:user_type)] : read_attribute(:user_type)
  end

  def status
    ( read_attribute(:active) ? I18n.t('site.labels.active') : I18n.t('site.labels.inactive') )
  end

  def full_name
    [first_name, last_name].compact.join " "
  end

  def admin?
    ROLE_ADMIN_SYSTEM == role
  end
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController

  before_action :validate_user_access!, only: [:new, :destroy]

  before_action :validate_user_edition!, only: [:edit]

  helper_method :url_form, :user, :places, :request_types, :user_filter_q

  def index
    @users = user_filter_q.result.order(created_at: :asc).paginate(:page => params[:page], :per_page => 2)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Registro creado con éxito"
      redirect_to admin_root_path
    else
      render :new
    end
  end

  def update
    user.update_attributes(user_params)
    if user.save
      flash[:success] = "Registro actualizado con éxito"
      redirect_to admin_root_path
    else
      render :edit
    end
  end

  def destroy
    if user.destroy
      flash[:success] = "Registro eliminado con éxito"
    else
      flash[:error] = "No se pudo eliminar el registro"
    end
    redirect_to admin_users_path
  end

  private
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :user_type, :active)
    end

    def user
      @user ||=
        case action_name
        when "edit", "update", "destroy"
          User.find(params[:id])
        end
    end

    def url_form
      @url_form ||=
        case action_name
        when "edit", "update"
          admin_user_path(user.id)
        when "create", "new"
          admin_users_path
        end
    end

    def user_filter_q
      @user_filter_q ||= User.ransack(params[:q]) 
    end

    def validate_user_access!
      redirect_to admin_root_path unless current_user.admin?
    end

    def validate_user_edition!
      unless current_user.admin?
        @user = User.find(params[:id]) rescue nil
        redirect_to admin_root_path unless current_user?(@user)
      end
    end

    def current_user? user
      user == current_user
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/test_logins_controller.rb
class TestLoginsController < ApplicationController

  def index
    
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  layout 'users/application'

  def after_sign_in_path_for(resource)
    admin_root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def bootstrap_class_for(flash_type)
    {
      success: 'alert-success',
      error: 'alert-danger',
      alert: 'alert-warning',
      notice: 'alert-primary'
    }[flash_type.to_sym] || flash_type.to_s
  end

  def link_to_edit url
    link_to url, class: "btn-edit-destroy", data: { turbolinks: false } do
      content_tag :p, "Editar"
    end
  end

  def link_to_destroy url
    link_to url, method: :delete, data: {confirm: '¿Está seguro que desea eliminar el registro?'}, class: "btn-edit-destroy" do
      content_tag :p, "Eliminar", class: "red-monza"
    end
  end

  def link_to_add url
    link_to url, class: "btn-link--action", data: { turbolinks: false } do
      content_tag(:p, "Agregar") + " " + content_tag(:i, "", class: "fas fa-plus-circle")
    end
  end
end

app/views/admin/users/_filter.html.haml
= search_form_for user_filter_q, url: admin_root_path, class: "form-search" do |f|
  .row
    .col-md-12
      .row
        .col-md-8
          = f.search_field :email_cont, placeholder: "Buscar por email"
        .col-md-4.text-right
          = button_tag type: 'submit' , class: "btn-submit" do
            %i.fa.fa-search
          = link_to admin_root_path, class: "btn-submit btn-clean" do
            %i.fa.fa-broom

app/views/admin/users/_form.html.haml
= simple_form_for user_form, url: url_form do |f|
  - if user_form.errors.any?
    .alert.alert-warning
      %strong= "Se encontraron #{pluralize(user_form.errors.count, "errores")}"

  = f.input :active, as: :boolean
  %br
  .user-fields
    .row
      .col-md-4
        = f.input :first_name
      .col-md-4
        = f.input :last_name
      .col-md-4
        - unless action_name.eql?("edit")
          = f.input :email
        - else
          .form-group
            = f.label "Correo electrónico:"
            %br
            = user_form.email
      .col-md-4
        = f.input :password
      .col-md-4
        = f.input :password_confirmation
      .col-md-4
        - if current_user.admin?
          = f.input :user_type, collection: User::ROLES.invert, include_blank:  "Seleccione rol"
        - else
          .form-group
            = f.label "Tipo de usuario:"
            %br
            = user_form.role(true)
               
    %br
    = link_to "Cancelar", admin_users_path, data: { turbolinks: false }, class: "btn btn-cancel"
    = f.submit class: "btn btn-primary"

app/views/admin/users/edit.html.haml
#header-admin
  .little-padding#border-bottom-light
    %h4= t("site.labels.edit_user").html_safe
.big-margin
  = render partial: "form", locals: { user_form: user }

app/views/admin/users/index.html.haml
#header-admin
  .little-padding#border-bottom-light
    %h4= t("site.labels.users").html_safe
  = render partial: "filter", locals: { user_filter_q: user_filter_q }

.little-padding
  .text-right
    = link_to_add new_admin_user_path if current_user.admin?

  %table.table.table-bordered.table-striped
    %thead
      %tr
        %th.text-center= "Fecha creación"
        %th.text-center= "Nombre"
        %th.text-center= "Apellido"
        %th.text-center= "Email"
        %th.text-center= "Tipo de Usuario"
        %th.text-center.th-100= "Estado"
        - if current_user.admin?
          %th.text-center{colspan: 2}= "Acciones"

    %tbody
      - @users.each do |user|
        %tr{style: ("background-color: #f2dede" if !user.active?)}
          %td.text-center= user.created_at.strftime("%d/%m/%Y")
          %td.text-center= user.first_name
          %td.text-center= user.last_name
          %td.text-center= user.email
          %td.text-center= user.role true
          %td.text-center= user.status
          - if current_user.admin?
            %td.text-center.th-100
              %strong= link_to_edit edit_admin_user_path(user.id)
            %td.text-center.th-100
              %strong= link_to_destroy admin_user_path(user.id)
            
  = will_paginate @user, renderer: BootstrapPagination::Rails

app/views/admin/users/new.html.haml
#header-admin
  .little-padding#border-bottom-light
    %h4= t("site.labels.new_user").html_safe
.big-margin
  = render partial: "form", locals: { user_form: user }

app/views/layouts/admin/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1, shrink-to-fit=no", :name => "viewport"}
    %title= t("site.labels.admin_title")
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body.bg-admin
    .admin-panel
      .title-admin.text-center
        %h5= "Administración de usuarios"
      .logout.text-right
        = link_to edit_admin_user_path(current_user), data: { turbolinks: false }, class: "" do
          = image_tag "user.png", class: "icon-user"
          .user-data
            = current_user.full_name
            %br
            %strong=current_user.role(true)
        = link_to destroy_user_session_path, class: "", id: "icon-logout", method: :delete do
          = image_tag "exit.png"
    - flash.each do |type, content|
      = render 'shared/flash', type: type, content: content
    .container
      = yield

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title= t("site.labels.title")
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/layouts/users/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1, shrink-to-fit=no", :name => "viewport"}
    %title= t("site.labels.user_title")
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    - flash.each do |type, content|
      = render 'shared/flash', type: type, content: content
    = yield

app/views/shared/_flash.html.haml
%div{:class => "alert #{bootstrap_class_for(type)} alert-dismissible fade show", :role => "alert"}
  %button.close{"data-aria-label" => "Close", "data-dismiss" => "alert", :type => "button"}
    %span{"aria-hidden" => "true"} ×
  .text.text-center
    = content

app/views/test_logins/index.html.haml
%br
%br
%br
%br
%br
.container
  .row
    .col-md-12.text-center
      = link_to new_user_session_path do
        %i.fa.fa-users.fa-10x
        %br
        %h5= "Iniciar sesión"